apiVersion: v1
kind: PersistentVolume
metadata:
  name: ptc-monitor-pv
  namespace: development
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/ptc-monitor

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ptc-monitor-pvc
  namespace: development
spec:
  accessModes: 
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi