name: PTC Monitor CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  
env:
  IMAGE_NAME: yashkanawade03/ptc-monitor

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up pythonn
      uses: actions/setup-python@v4
      with :
        python-version: '3.11'
      
    - name: Install dependencies
      run: |
        cd capstone/ptc-monitor
        pip install -r requirements.txt
        pip install pytest httpx
    
    - name: Run tests
      env: 
        APP_NAME: test-app
        APP_ENV: test
        APP_VERSION: 1.0.0
      run: |
        cd capstone/ptc-monitor
        python -m pytest tests/ -v
  build-and-push:
    name: Build and push docker image
    runs-on: ubuntu-latest
    needs: tests
    if: github.ref == refs/head/main && github.event_name == 'push'

    steps:
    - name: checkout code
      uses: actions/checkout@v3
    
    - name: docker set up
      uses: docker/setup-buildx-action@v2

    - name: Login to docker
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: extract metadata
      id: meta
      run: |
        echo "sha_short=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT
        echo "image_tag=${{ env.IMAGE_NAME }}:(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

    - name: build and push docker image 
      uses: docker/build-push-action@v4
      with:
        context: ./capstone/ptc-monitor
        push: true
        tags: |
          ${{ env.IMAGE_NAME }}:latest
          ${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.sha_short }}
          
    - name: Summary
      run: |
        echo "✅ Pipeline complete"
        echo "Image: ${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.sha_short }}"
        echo "Also tagged as: ${{ env.IMAGE_NAME }}:latest"



